name: Reporte Diario desde Base de Datos

on:
  schedule:
    # Ejecutar todos los días a las 2:00 PM UTC = 9:00 AM Bogotá (UTC-5)
    - cron: '0 14 * * *'
  workflow_dispatch:  # Permite ejecución manual

jobs:
  generar-reporte-diario:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Crear directorios necesarios
        run: |
          mkdir -p data output
      
      - name: Descargar base de datos actual
        uses: actions/download-artifact@v4
        with:
          name: base-datos-notas-credito
          path: data/
        continue-on-error: true
      
      - name: Verificar base de datos
        run: |
          if [ -f data/notas_credito.db ]; then
            echo "✅ Base de datos encontrada"
            ls -lh data/notas_credito.db
          else
            echo "❌ Base de datos no encontrada"
            echo "Ejecute el proceso principal al menos una vez para crear la BD"
            exit 1
          fi
      
      - name: Generar y enviar reporte
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          DESTINATARIOS: ${{ secrets.DESTINATARIOS }}
          DB_PATH: ./data/notas_credito.db
        run: python reporte_diario.py
      
      - name: Cargar reporte como artefacto
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reporte-diario
          path: output/reporte_diario_*.html
          retention-days: 30
